spring:
  application:
    name: finance-chatbot
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:admin}"
    password: "${RABBITMQ_PASSWORD:admin123}"
    virtual-host: "${RABBITMQ_VHOST:/}"

server:
  port: 8081

logging:
  level:
    root: INFO
    com.finance.chatboot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

telegram:
  bot:
    token: "${TELEGRAM_BOT_TOKEN}"
    username: "${TELEGRAM_BOT_USERNAME}"
  webhook:
    url: "${TELEGRAM_WEBHOOK_URL}"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
